"""tracked products and notifications

Revision ID: 1ea946afe7ef
Revises: e2e438553863
Create Date: 2026-07-25 21:04:59.571321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1ea946afe7ef'
down_revision: Union[str, None] = 'e2e438553863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracked_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notify_on_any_drop', sa.Boolean(), nullable=False),
    sa.Column('last_seen_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('last_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_tracked_products_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tracked_products_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tracked_products')),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_tracked_user_product')
    )
    op.create_index(op.f('ix_tracked_products_is_active'), 'tracked_products', ['is_active'], unique=False)
    op.create_index(op.f('ix_tracked_products_product_id'), 'tracked_products', ['product_id'], unique=False)
    op.create_index(op.f('ix_tracked_products_user_id'), 'tracked_products', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tracked_product_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=False),
    sa.Column('old_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('new_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('dedup_key', sa.String(length=200), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'sent', 'failed', 'skipped')", name=op.f('ck_notifications_notification_status_allowed')),
    sa.CheckConstraint("type IN ('price_drop', 'back_in_stock', 'target_reached')", name=op.f('ck_notifications_type_allowed')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_notifications_product_id_products'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tracked_product_id'], ['tracked_products.id'], name=op.f('fk_notifications_tracked_product_id_tracked_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('dedup_key', name='uq_notification_dedup_key')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_tracked_product_id'), 'notifications', ['tracked_product_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_tracked_product_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_tracked_products_user_id'), table_name='tracked_products')
    op.drop_index(op.f('ix_tracked_products_product_id'), table_name='tracked_products')
    op.drop_index(op.f('ix_tracked_products_is_active'), table_name='tracked_products')
    op.drop_table('tracked_products')
    # ### end Alembic commands ###
