"""core: offers canonical dictionaries matching

Revision ID: 336d8cc4267a
Revises: fb0762d20565
Create Date: 2026-07-25 07:33:44.352371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '336d8cc4267a'
down_revision: Union[str, None] = 'fb0762d20565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', postgresql.CITEXT(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brands')),
    sa.UniqueConstraint('name', name=op.f('uq_brands_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_brands_slug'))
    )
    op.create_table('colors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name_ru', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_colors')),
    sa.UniqueConstraint('code', name=op.f('uq_colors_code'))
    )
    op.create_table('part_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name_ru', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_part_types')),
    sa.UniqueConstraint('code', name=op.f('uq_part_types_code'))
    )
    op.create_table('quality_tiers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name_ru', sa.String(length=120), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quality_tiers')),
    sa.UniqueConstraint('code', name=op.f('uq_quality_tiers_code'))
    )
    op.create_table('stopwords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word', postgresql.CITEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stopwords')),
    sa.UniqueConstraint('word', name=op.f('uq_stopwords_word'))
    )
    op.create_table('color_synonyms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('synonym', postgresql.CITEXT(), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], name=op.f('fk_color_synonyms_color_id_colors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_color_synonyms')),
    sa.UniqueConstraint('synonym', name='uq_color_synonyms_synonym')
    )
    op.create_index(op.f('ix_color_synonyms_color_id'), 'color_synonyms', ['color_id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('model_key', postgresql.CITEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_devices_brand_id_brands'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('model_key', name=op.f('uq_devices_model_key'))
    )
    op.create_index(op.f('ix_devices_brand_id'), 'devices', ['brand_id'], unique=False)
    op.create_table('part_type_synonyms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('part_type_id', sa.Integer(), nullable=False),
    sa.Column('synonym', postgresql.CITEXT(), nullable=False),
    sa.ForeignKeyConstraint(['part_type_id'], ['part_types.id'], name=op.f('fk_part_type_synonyms_part_type_id_part_types'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_part_type_synonyms')),
    sa.UniqueConstraint('synonym', name=op.f('uq_part_type_synonyms_synonym'))
    )
    op.create_index(op.f('ix_part_type_synonyms_part_type_id'), 'part_type_synonyms', ['part_type_id'], unique=False)
    op.create_table('quality_tier_synonyms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quality_tier_id', sa.Integer(), nullable=False),
    sa.Column('synonym', postgresql.CITEXT(), nullable=False),
    sa.ForeignKeyConstraint(['quality_tier_id'], ['quality_tiers.id'], name=op.f('fk_quality_tier_synonyms_quality_tier_id_quality_tiers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quality_tier_synonyms')),
    sa.UniqueConstraint('synonym', name=op.f('uq_quality_tier_synonyms_synonym'))
    )
    op.create_index(op.f('ix_quality_tier_synonyms_quality_tier_id'), 'quality_tier_synonyms', ['quality_tier_id'], unique=False)
    op.create_table('clusters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('part_type_id', sa.Integer(), nullable=False),
    sa.Column('offers_count', sa.Integer(), nullable=False),
    sa.Column('min_price_retail', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('min_price_opt', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_clusters_device_id_devices'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['part_type_id'], ['part_types.id'], name=op.f('fk_clusters_part_type_id_part_types'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clusters')),
    sa.UniqueConstraint('device_id', 'part_type_id', name='uq_clusters_device_id')
    )
    op.create_index(op.f('ix_clusters_device_id'), 'clusters', ['device_id'], unique=False)
    op.create_index(op.f('ix_clusters_part_type_id'), 'clusters', ['part_type_id'], unique=False)
    op.create_table('device_aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('alias', postgresql.CITEXT(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_device_aliases_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_aliases')),
    sa.UniqueConstraint('alias', name=op.f('uq_device_aliases_alias'))
    )
    op.create_index(op.f('ix_device_aliases_device_id'), 'device_aliases', ['device_id'], unique=False)
    op.create_table('store_offers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('source_sku', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('normalized_title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('price_retail', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_opt', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_old', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('stock_status', sa.String(length=20), nullable=False),
    sa.Column('stock_qty', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('match_status', sa.String(length=20), nullable=False),
    sa.Column('match_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('price_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("match_status IN ('unmatched', 'auto', 'manual', 'rejected')", name=op.f('ck_store_offers_match_status_allowed')),
    sa.CheckConstraint("stock_status IN ('in_stock', 'low', 'out', 'preorder', 'unknown')", name=op.f('ck_store_offers_stock_status_allowed')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_store_offers_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_store_offers_product_id_products'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_store_offers_store_id_stores'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_store_offers')),
    sa.UniqueConstraint('store_id', 'source_sku', name='uq_store_offers_store_id')
    )
    op.create_index(op.f('ix_store_offers_category_id'), 'store_offers', ['category_id'], unique=False)
    op.create_index(op.f('ix_store_offers_product_id'), 'store_offers', ['product_id'], unique=False)
    op.create_index(op.f('ix_store_offers_store_id'), 'store_offers', ['store_id'], unique=False)
    op.create_table('match_candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name=op.f('ck_match_candidates_status_allowed')),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_match_candidates_decided_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['offer_id'], ['store_offers.id'], name=op.f('fk_match_candidates_offer_id_store_offers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_match_candidates_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_candidates')),
    sa.UniqueConstraint('offer_id', 'product_id', name='uq_match_candidates_offer_id')
    )
    op.create_index(op.f('ix_match_candidates_offer_id'), 'match_candidates', ['offer_id'], unique=False)
    op.create_index(op.f('ix_match_candidates_product_id'), 'match_candidates', ['product_id'], unique=False)
    op.create_table('offer_price_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('price_retail', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_opt', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('stock_status', sa.String(length=20), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['store_offers.id'], name=op.f('fk_offer_price_history_offer_id_store_offers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offer_price_history'))
    )
    op.create_index(op.f('ix_offer_price_history_offer_id'), 'offer_price_history', ['offer_id'], unique=False)
    op.drop_index('ix_price_history_product_id', table_name='price_history')
    op.drop_table('price_history')
    op.add_column('products', sa.Column('cluster_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('quality_tier_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('brand_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('key_attrs', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('canonical_key', sa.String(length=300), nullable=False))
    op.add_column('products', sa.Column('canonical_name', sa.String(length=500), nullable=False))
    op.drop_index('ix_products_category_id', table_name='products')
    op.drop_index('ix_products_normalized_name', table_name='products')
    op.drop_index('ix_products_store_id', table_name='products')
    op.create_index(op.f('ix_products_brand_id'), 'products', ['brand_id'], unique=False)
    op.create_index(op.f('ix_products_cluster_id'), 'products', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_products_quality_tier_id'), 'products', ['quality_tier_id'], unique=False)
    op.create_unique_constraint(op.f('uq_products_canonical_key'), 'products', ['canonical_key'])
    op.drop_constraint(op.f('fk_products_store_id_stores'), 'products', type_='foreignkey')
    op.drop_constraint(op.f('fk_products_category_id_categories'), 'products', type_='foreignkey')
    op.create_foreign_key(op.f('fk_products_cluster_id_clusters'), 'products', 'clusters', ['cluster_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_products_brand_id_brands'), 'products', 'brands', ['brand_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_products_quality_tier_id_quality_tiers'), 'products', 'quality_tiers', ['quality_tier_id'], ['id'], ondelete='SET NULL')
    op.drop_column('products', 'store_id')
    op.drop_column('products', 'old_price')
    op.drop_column('products', 'name')
    op.drop_column('products', 'product_url')
    op.drop_column('products', 'normalized_name')
    op.drop_column('products', 'image_url')
    op.drop_column('products', 'price')
    op.drop_column('products', 'description')
    op.drop_column('products', 'external_id')
    op.drop_column('products', 'last_updated')
    op.drop_column('products', 'in_stock')
    op.drop_column('products', 'currency')
    op.drop_column('products', 'category_id')
    op.alter_column('search_history', 'filters',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
    op.execute(
        "CREATE INDEX ix_store_offers_normalized_title_trgm "
        "ON store_offers USING gin (normalized_title gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX ix_products_canonical_name_trgm "
        "ON products USING gin (canonical_name gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX ix_device_aliases_alias_trgm "
        "ON device_aliases USING gin ((alias::text) gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX ix_part_type_synonyms_synonym_trgm "
        "ON part_type_synonyms USING gin ((synonym::text) gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX ix_quality_tier_synonyms_synonym_trgm "
        "ON quality_tier_synonyms USING gin ((synonym::text) gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX ix_store_offers_price_retail_active "
        "ON store_offers (price_retail) WHERE is_active"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('search_history', 'filters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('products', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('in_stock', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('external_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('description', sa.VARCHAR(length=2000), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('normalized_name', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('product_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('name', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('old_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_products_quality_tier_id_quality_tiers'), 'products', type_='foreignkey')
    op.drop_constraint(op.f('fk_products_brand_id_brands'), 'products', type_='foreignkey')
    op.drop_constraint(op.f('fk_products_cluster_id_clusters'), 'products', type_='foreignkey')
    op.create_foreign_key(op.f('fk_products_category_id_categories'), 'products', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_products_store_id_stores'), 'products', 'stores', ['store_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('uq_products_canonical_key'), 'products', type_='unique')
    op.drop_index(op.f('ix_products_quality_tier_id'), table_name='products')
    op.drop_index(op.f('ix_products_cluster_id'), table_name='products')
    op.drop_index(op.f('ix_products_brand_id'), table_name='products')
    op.create_index('ix_products_store_id', 'products', ['store_id'], unique=False)
    op.create_index('ix_products_normalized_name', 'products', ['normalized_name'], unique=False)
    op.create_index('ix_products_category_id', 'products', ['category_id'], unique=False)
    op.drop_column('products', 'canonical_name')
    op.drop_column('products', 'canonical_key')
    op.drop_column('products', 'key_attrs')
    op.drop_column('products', 'brand_id')
    op.drop_column('products', 'quality_tier_id')
    op.drop_column('products', 'cluster_id')
    op.create_table('price_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='price_history_product_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='price_history_pkey')
    )
    op.create_index('ix_price_history_product_id', 'price_history', ['product_id'], unique=False)
    op.drop_index(op.f('ix_offer_price_history_offer_id'), table_name='offer_price_history')
    op.drop_table('offer_price_history')
    op.drop_index(op.f('ix_match_candidates_product_id'), table_name='match_candidates')
    op.drop_index(op.f('ix_match_candidates_offer_id'), table_name='match_candidates')
    op.drop_table('match_candidates')
    op.drop_index(op.f('ix_store_offers_store_id'), table_name='store_offers')
    op.drop_index(op.f('ix_store_offers_product_id'), table_name='store_offers')
    op.drop_index(op.f('ix_store_offers_category_id'), table_name='store_offers')
    op.drop_table('store_offers')
    op.drop_index(op.f('ix_device_aliases_device_id'), table_name='device_aliases')
    op.drop_table('device_aliases')
    op.drop_index(op.f('ix_clusters_part_type_id'), table_name='clusters')
    op.drop_index(op.f('ix_clusters_device_id'), table_name='clusters')
    op.drop_table('clusters')
    op.drop_index(op.f('ix_quality_tier_synonyms_quality_tier_id'), table_name='quality_tier_synonyms')
    op.drop_table('quality_tier_synonyms')
    op.drop_index(op.f('ix_part_type_synonyms_part_type_id'), table_name='part_type_synonyms')
    op.drop_table('part_type_synonyms')
    op.drop_index(op.f('ix_devices_brand_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_color_synonyms_color_id'), table_name='color_synonyms')
    op.drop_table('color_synonyms')
    op.drop_table('stopwords')
    op.drop_table('quality_tiers')
    op.drop_table('part_types')
    op.drop_table('colors')
    op.drop_table('brands')
    # ### end Alembic commands ###
