"""tracked product initial price baseline

Revision ID: 51e60c6b40f1
Revises: 1ea946afe7ef
Create Date: 2026-07-25 21:21:50.308454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '51e60c6b40f1'
down_revision: Union[str, None] = '1ea946afe7ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracked_products', sa.Column('initial_price', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracked_products', 'initial_price')
    # ### end Alembic commands ###
