"""refresh tokens and protect price history from store deletion

Revision ID: a0ddb53734c7
Revises: 51e60c6b40f1
Create Date: 2026-07-25 21:46:06.029863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a0ddb53734c7'
down_revision: Union[str, None] = '51e60c6b40f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=50), nullable=True),
    sa.Column('replaced_by_jti', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.drop_constraint('fk_store_offers_store_id_stores', 'store_offers', type_='foreignkey')
    op.create_foreign_key(op.f('fk_store_offers_store_id_stores'), 'store_offers', 'stores', ['store_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint('fk_store_offers_store_id_stores', 'store_offers', type_='foreignkey')
    op.create_foreign_key(
        'fk_store_offers_store_id_stores',
        'store_offers',
        'stores',
        ['store_id'],
        ['id'],
        ondelete='RESTRICT',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_store_offers_store_id_stores'), 'store_offers', type_='foreignkey')
    op.create_foreign_key('fk_store_offers_store_id_stores', 'store_offers', 'stores', ['store_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_constraint('fk_store_offers_store_id_stores', 'store_offers', type_='foreignkey')
    op.create_foreign_key(
        'fk_store_offers_store_id_stores',
        'store_offers',
        'stores',
        ['store_id'],
        ['id'],
        ondelete='CASCADE',
    )
    # ### end Alembic commands ###
