"""broadcast campaigns

Revision ID: ca1001d72baa
Revises: d1932d23f697
Create Date: 2026-09-08 22:03:28.417122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ca1001d72baa'
down_revision: Union[str, None] = 'd1932d23f697'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broadcasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('audience', sa.Enum('all_active', 'verified', 'subscribers', 'custom', name='broadcastaudience'), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('html', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'queued', 'running', 'completed', 'failed', 'cancelled', name='broadcaststatus'), nullable=False),
    sa.Column('total_recipients', sa.Integer(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('recipient_emails', postgresql.ARRAY(sa.String(length=320)), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_broadcasts_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_broadcasts'))
    )
    op.create_index(op.f('ix_broadcasts_created_by'), 'broadcasts', ['created_by'], unique=False)
    op.create_index(op.f('ix_broadcasts_status'), 'broadcasts', ['status'], unique=False)
    op.create_table('broadcast_recipients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('broadcast_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sending', 'sent', 'failed', name='recipientstatus'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['broadcast_id'], ['broadcasts.id'], name=op.f('fk_broadcast_recipients_broadcast_id_broadcasts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_broadcast_recipients_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_broadcast_recipients')),
    sa.UniqueConstraint('broadcast_id', 'email', name='uq_broadcast_recipients_broadcast_email')
    )
    op.create_index(op.f('ix_broadcast_recipients_broadcast_id'), 'broadcast_recipients', ['broadcast_id'], unique=False)
    op.create_index(op.f('ix_broadcast_recipients_status'), 'broadcast_recipients', ['status'], unique=False)
    op.create_index(op.f('ix_broadcast_recipients_user_id'), 'broadcast_recipients', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_broadcast_recipients_user_id'), table_name='broadcast_recipients')
    op.drop_index(op.f('ix_broadcast_recipients_status'), table_name='broadcast_recipients')
    op.drop_index(op.f('ix_broadcast_recipients_broadcast_id'), table_name='broadcast_recipients')
    op.drop_table('broadcast_recipients')
    op.drop_index(op.f('ix_broadcasts_status'), table_name='broadcasts')
    op.drop_index(op.f('ix_broadcasts_created_by'), table_name='broadcasts')
    op.drop_table('broadcasts')
    # ### end Alembic commands ###
